language: cpp
compiler: gcc
install: 

  - conda env create -f scripts/mapd-deps-conda-dev-env.yml --force -n omnisci-dev
  - conda activate omnisci-dev
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
